package main

import (
	"context"
	"fmt"
	"log"

	"hardcoreai-rag/indexing"
	"hardcoreai-rag/retrieval"
	"hardcoreai-rag/storage"
)

func main() {

	fmt.Println("Initializing Live Retrieval Verification...")

	// 1. Open the real database generated by the parser
	db, err := storage.Open("data/rag.db", "")
	if err != nil {
		log.Fatalf("Failed to open database: %v", err)
	}
	defer db.Close()

	// 2. Setup deterministic offline local embedder
	embedder := indexing.NewEmbedder()
	engine := retrieval.NewEngine(db, embedder)
	
	query := "USART register description"
	opts := retrieval.RetrievalOptions{
		K:          3,
		ChipFamily: "STM32F4", // Apply dynamic SQL filter
		MaxTokens:  2500,     // strict token budget
	}

	fmt.Printf("\nRunning End-to-End Retrieval Engine for query: %q\n", query)
	fmt.Printf("Options: ChipFamily=%s, K=%d, MaxTokens=%d\n\n", opts.ChipFamily, opts.K, opts.MaxTokens)

	// 3. Execute the full orchestrator retrieve pipeline
	res, err := engine.Retrieve(context.Background(), query, opts)
	if err != nil {
		log.Fatalf("Engine.Retrieve failed: %v", err)
	}

	if len(res.Chunks) == 0 {
		fmt.Println("Warning: No chunks retrieved. Make sure data/rag.db is populated.")
		return
	}

	// 4. Print out the retrieved and ranked chunks with score breakdown
	fmt.Println("=== RANKED SEARCH RESULTS ===")
	for i, chunk := range res.Chunks {
		fmt.Printf("Rank %d [Chunk ID: %d]\n", i+1, chunk.ChunkID)
		fmt.Printf("  • File:       %s\n", chunk.Filename)
		fmt.Printf("  • Section:    %s\n", chunk.SectionTitle)
		fmt.Printf("  • Peripheral: %s\n", chunk.Peripheral)
		fmt.Printf("  • Register:   %s\n", chunk.RegisterName)
		fmt.Printf("  • Scores:     Semantic=%.4f | FTS=%.4f | Boost=%.4f | FINAL=%.4f\n", 
			chunk.SemanticScore, chunk.FTSScore, chunk.MetadataBoost, chunk.FinalScore)
		fmt.Printf("  • Text Snippet:\n    \"%s...\"\n\n", truncateText(chunk.ChunkText, 150))
	}

	// 5. Print the formatted LLM-ready Context Builder output
	fmt.Println("=== LLM-READY CONTEXT WINDOW ===")
	fmt.Printf("Used Chunks: %d | Dropped Chunks: %d\n", res.ChunksUsed, res.ChunksDropped)
	fmt.Println("----------------------------------------------------------------------")
	fmt.Println(res.Context)
	fmt.Println("----------------------------------------------------------------------")
}

func truncateText(s string, maxLen int) string {
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen]
}
