-- HardcoreAI workbench schema
-- Reconciles the existing public schema (components, pins, projects,
-- project_components, project_connections) with what the workbench IDE
-- needs: visual/layout data, per-project code files, and viewport state.
--
-- Safe to run on a fresh database or an existing one: every statement is
-- guarded with IF NOT EXISTS / IF EXISTS.

-- ---------------------------------------------------------------------------
-- Base tables (created only if the project is starting empty)
-- ---------------------------------------------------------------------------

create table if not exists public.components (
    id            bigint generated by default as identity primary key,
    name          text not null,
    library_name  text,
    description   text,
    is_controller boolean default false,
    cpp_class_name text,
    header_file   text,
    created_at    timestamptz default now()
);

create table if not exists public.pins (
    id            bigint generated by default as identity primary key,
    component_id  bigint not null references public.components (id) on delete cascade,
    label         text not null,
    voltage       real,
    is_input      boolean default false,
    is_output     boolean default false,
    capabilities  text,
    created_at    timestamptz default now()
);

create table if not exists public.projects (
    id          bigint generated by default as identity primary key,
    name        text not null,
    user_id     bigint,
    created_at  timestamptz default now()
);

create table if not exists public.project_components (
    id            bigint generated by default as identity primary key,
    project_id    bigint not null references public.projects (id) on delete cascade,
    component_id  bigint not null references public.components (id) on delete restrict,
    instance_name text not null,
    created_at    timestamptz default now()
);

create table if not exists public.project_connections (
    id               bigint generated by default as identity primary key,
    project_id       bigint not null references public.projects (id) on delete cascade,
    from_instance_id bigint not null references public.project_components (id) on delete cascade,
    from_pin_label   text not null,
    to_instance_id   bigint not null references public.project_components (id) on delete cascade,
    to_pin_label     text not null,
    created_at       timestamptz default now()
);

-- ---------------------------------------------------------------------------
-- components: add visual / catalogue metadata used by the workbench renderer
-- ---------------------------------------------------------------------------

alter table public.components add column if not exists category    text    not null default 'Component';
alter table public.components add column if not exists visual_type text    not null default 'generic';
alter table public.components add column if not exists thumbnail   text    not null default 'generic';
alter table public.components add column if not exists width       integer not null default 140;
alter table public.components add column if not exists height      integer not null default 100;
alter table public.components add column if not exists description text;
alter table public.components add column if not exists updated_at  timestamptz not null default now();

-- A stable string slug so the frontend/firmware code can refer to a component
-- without depending on the integer id (e.g. "stm32-blue-pill").
alter table public.components add column if not exists slug text;
update public.components set slug = lower(regexp_replace(name, '[^a-zA-Z0-9]+', '-', 'g'))
    where slug is null;
alter table public.components alter column slug set not null;
create unique index if not exists components_slug_key on public.components (slug);

-- ---------------------------------------------------------------------------
-- pins: add placement (side/x/y) and a single role used by firmware generation
-- ---------------------------------------------------------------------------

alter table public.pins add column if not exists name text;
alter table public.pins add column if not exists side text not null default 'left';
alter table public.pins add column if not exists x    real not null default 0;
alter table public.pins add column if not exists y    real not null default 0;
alter table public.pins add column if not exists role text not null default 'gpio';

-- pins.name is the machine identifier ("L0_VB"); fall back to label if unset.
update public.pins set name = label where name is null;
alter table public.pins alter column name set not null;

-- ---------------------------------------------------------------------------
-- project_components: placement of an instance on the workbench canvas
-- ---------------------------------------------------------------------------

alter table public.project_components add column if not exists x        real    not null default 480;
alter table public.project_components add column if not exists y        real    not null default 280;
alter table public.project_components add column if not exists rotation integer not null default 0;
alter table public.project_components add column if not exists config   jsonb   not null default '{}'::jsonb;

-- ---------------------------------------------------------------------------
-- projects: workbench needs a name/description + viewport + updated_at
-- ---------------------------------------------------------------------------

alter table public.projects add column if not exists description text not null default '';
alter table public.projects add column if not exists updated_at  timestamptz not null default now();
alter table public.projects add column if not exists viewport    jsonb not null default '{"x": 0, "y": 0, "zoom": 1}'::jsonb;
-- user_id stays nullable (no auth yet).
alter table public.projects alter column user_id drop not null;

-- ---------------------------------------------------------------------------
-- code_files: per-project source files (generated firmware, README, ...)
-- ---------------------------------------------------------------------------

create table if not exists public.code_files (
    id         bigint generated by default as identity primary key,
    project_id bigint not null references public.projects (id) on delete cascade,
    path       text not null,
    language   text not null default 'c',
    content    text not null default '',
    updated_at timestamptz not null default now(),
    unique (project_id, path)
);

create index if not exists code_files_project_idx on public.code_files (project_id);
create index if not exists pins_component_idx on public.pins (component_id);
create index if not exists project_components_project_idx on public.project_components (project_id);
create index if not exists project_connections_project_idx on public.project_connections (project_id);

-- ---------------------------------------------------------------------------
-- updated_at trigger
-- ---------------------------------------------------------------------------

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
    new.updated_at = now();
    return new;
end;
$$;

drop trigger if exists projects_touch on public.projects;
create trigger projects_touch before update on public.projects
    for each row execute function public.touch_updated_at();

drop trigger if exists code_files_touch on public.code_files;
create trigger code_files_touch before update on public.code_files
    for each row execute function public.touch_updated_at();

drop trigger if exists components_touch on public.components;
create trigger components_touch before update on public.components
    for each row execute function public.touch_updated_at();
